spring.application.name=design_patterns
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop

# R2DBC props
spring.r2dbc.url=r2dbc:postgresql://localhost:5433/
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres