spring.application.name=design_patterns
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

# --- KAFKA CONFIG ---

# connection/networking config
# bootstrap-servers: list of addresses to brokers
spring.kafka.bootstrap-servers=localhost:9092

# Kafka producer config
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

# Kafka consumer config
spring.kafka.consumer.group-id=payment-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=org.example.design_patterns.kafka.*


# R2DBC props
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres

# flyway conf
spring.flyway.enabled=true
spring.flyway.url=jdbc:postgresql://localhost:5432/
spring.flyway.user=postgres
spring.flyway.password=postgres
spring.flyway.validate-migration-naming=true