spring.application.name=design_patterns
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

# R2DBC props
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres

# flyway conf
spring.flyway.enabled=true
spring.flyway.url=jdbc:postgresql://localhost:5432/
spring.flyway.user=postgres
spring.flyway.password=postgres
spring.flyway.validate-migration-naming=true